name: ServerManger
version: '1.0'
main: io.dynhop.paperPlugin.PaperPlugin
api-version: '1.21'
load: STARTUP
authors: [ Zero MØtion ]
description: Server Manager Plugin, registers this server with the proxy
website: dynhop.io
